package GUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class TeacherSidePanel {
    private JPanel BatchesPanel;
    private JPanel BatchSubPanel;
    private JPanel BatchActionButtonsPanel;
    private JButton addBatchButton;
    private JButton updateBatchButton;
    private JButton deleteBatchButton;
    private JPanel BatchSearchBarPanel;
    private JScrollPane BatchPanel;
    private JTable BatchTable;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        BatchesPanel = new JPanel();
        BatchesPanel.setLayout(new BorderLayout(0, 0));
        BatchesPanel.setBackground(new Color(-920071));
        panel1.add(BatchesPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        BatchesPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), "", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, Font.BOLD, 20, BatchesPanel.getFont()), new Color(-14800581)));
        BatchSubPanel = new JPanel();
        BatchSubPanel.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        BatchesPanel.add(BatchSubPanel, BorderLayout.CENTER);
        BatchSubPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        BatchActionButtonsPanel = new JPanel();
        BatchActionButtonsPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        BatchSubPanel.add(BatchActionButtonsPanel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        BatchActionButtonsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        addBatchButton = new JButton();
        addBatchButton.setActionCommand("Add Batch");
        addBatchButton.setBackground(new Color(-15681151));
        addBatchButton.setBorderPainted(false);
        addBatchButton.setFocusPainted(false);
        addBatchButton.setForeground(new Color(-1));
        addBatchButton.setPreferredSize(new Dimension(180, 40));
        addBatchButton.setText("Add Batch");
        BatchActionButtonsPanel.add(addBatchButton);
        updateBatchButton = new JButton();
        updateBatchButton.setActionCommand("Update Batch");
        updateBatchButton.setBackground(new Color(-12877066));
        updateBatchButton.setBorderPainted(false);
        updateBatchButton.setFocusPainted(false);
        updateBatchButton.setForeground(new Color(-1));
        updateBatchButton.setPreferredSize(new Dimension(180, 40));
        updateBatchButton.setText("Update Batch");
        BatchActionButtonsPanel.add(updateBatchButton);
        deleteBatchButton = new JButton();
        deleteBatchButton.setActionCommand("Delete Batch");
        deleteBatchButton.setBackground(new Color(-1096636));
        deleteBatchButton.setBorderPainted(false);
        deleteBatchButton.setFocusPainted(false);
        deleteBatchButton.setForeground(new Color(-1));
        deleteBatchButton.setPreferredSize(new Dimension(180, 40));
        deleteBatchButton.setText("Delete Batch");
        BatchActionButtonsPanel.add(deleteBatchButton);
        BatchSearchBarPanel = new JPanel();
        BatchSearchBarPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        BatchSearchBarPanel.setBackground(new Color(-920071));
        BatchSubPanel.add(BatchSearchBarPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        BatchSearchBarPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-1906448)));
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setText("Welcome Back -");
        BatchSearchBarPanel.add(label1);
        final JLabel label2 = new JLabel();
        label2.setText("Label");
        BatchSearchBarPanel.add(label2);
        BatchPanel = new JScrollPane();
        BatchSubPanel.add(BatchPanel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        BatchPanel.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$("Consolas", Font.BOLD, 20, BatchPanel.getFont()), null));
        BatchTable = new JTable();
        BatchTable.setAutoCreateRowSorter(false);
        BatchTable.setGridColor(new Color(-920071));
        BatchPanel.setViewportView(BatchTable);
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, Font.BOLD, 20, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-14800581));
        label3.setText("Your Schedules");
        BatchSubPanel.add(label3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

}
